### ISSUE TITLE
argus allows duplicate field names

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#59] opened 2020-09-29 18:27 UTC
argus accepts json payloads with non-unique object names:
e.g.
{"identifier" : "minimal0","data": {"mini":"mouse"},"ttl":300,"identifier" : "minimal1","data": {"mini":"mouse"},"ttl":600}

which is stored as (ignore ttl decreasing value):
{"identifier":"minimal1","data":{"mini":"mouse"},"ttl":578}

It replaces the value of the  first occurrence with the value of the last occurrence of the name.  The json syntax doesn't require unique identifiers.  The json lint validator flags this as invalid json.

**Comment by joe94** [comment] 2020-11-11 19:10
Good to keep this around but I doubt we can change this as JSON parsing is done by the golang standard library.

**Comment by joe94** [comment] 2020-11-13 22:55
Duplicate of #60

**Closed by joe94** 2020-11-13 22:55 UTC
Labels: bug, needs discussion
